#pragma once

namespace ho {
    enum InputKey {
        // Mouse Buttons
        INPUT_KEY_MOUSE_LEFT,
        INPUT_KEY_MOUSE_RIGHT,
        INPUT_KEY_MOUSE_MIDDLE,
        INPUT_KEY_MOUSE_X1,
        INPUT_KEY_MOUSE_X2,

        // Keyboard - Control Keys
        INPUT_KEY_BACKSPACE,
        INPUT_KEY_TAB,
        INPUT_KEY_CLEAR,
        INPUT_KEY_ENTER,
        INPUT_KEY_SHIFT,
        INPUT_KEY_CONTROL,
        INPUT_KEY_ALT,
        INPUT_KEY_PAUSE,
        INPUT_KEY_CAPS_LOCK,
        INPUT_KEY_ESCAPE,
        INPUT_KEY_SPACE,
        INPUT_KEY_PAGE_UP,
        INPUT_KEY_PAGE_DOWN,
        INPUT_KEY_END,
        INPUT_KEY_HOME,
        INPUT_KEY_LEFT,
        INPUT_KEY_UP,
        INPUT_KEY_RIGHT,
        INPUT_KEY_DOWN,
        INPUT_KEY_SELECT,
        INPUT_KEY_PRINT,
        INPUT_KEY_EXECUTE,
        INPUT_KEY_PRINT_SCREEN,
        INPUT_KEY_INSERT,
        INPUT_KEY_DELETE,
        INPUT_KEY_HELP,

        // Number Keys
        INPUT_KEY_0,
        INPUT_KEY_1,
        INPUT_KEY_2,
        INPUT_KEY_3,
        INPUT_KEY_4,
        INPUT_KEY_5,
        INPUT_KEY_6,
        INPUT_KEY_7,
        INPUT_KEY_8,
        INPUT_KEY_9,

        // Alphabet Keys
        INPUT_KEY_A,
        INPUT_KEY_B,
        INPUT_KEY_C,
        INPUT_KEY_D,
        INPUT_KEY_E,
        INPUT_KEY_F,
        INPUT_KEY_G,
        INPUT_KEY_H,
        INPUT_KEY_I,
        INPUT_KEY_J,
        INPUT_KEY_K,
        INPUT_KEY_L,
        INPUT_KEY_M,
        INPUT_KEY_N,
        INPUT_KEY_O,
        INPUT_KEY_P,
        INPUT_KEY_Q,
        INPUT_KEY_R,
        INPUT_KEY_S,
        INPUT_KEY_T,
        INPUT_KEY_U,
        INPUT_KEY_V,
        INPUT_KEY_W,
        INPUT_KEY_X,
        INPUT_KEY_Y,
        INPUT_KEY_Z,

        // Function Keys
        INPUT_KEY_F1,
        INPUT_KEY_F2,
        INPUT_KEY_F3,
        INPUT_KEY_F4,
        INPUT_KEY_F5,
        INPUT_KEY_F6,
        INPUT_KEY_F7,
        INPUT_KEY_F8,
        INPUT_KEY_F9,
        INPUT_KEY_F10,
        INPUT_KEY_F11,
        INPUT_KEY_F12,
        INPUT_KEY_F13,
        INPUT_KEY_F14,
        INPUT_KEY_F15,
        INPUT_KEY_F16,
        INPUT_KEY_F17,
        INPUT_KEY_F18,
        INPUT_KEY_F19,
        INPUT_KEY_F20,
        INPUT_KEY_F21,
        INPUT_KEY_F22,
        INPUT_KEY_F23,
        INPUT_KEY_F24,

        // Numpad Keys
        INPUT_KEY_NUM_LOCK,
        INPUT_KEY_SCROLL_LOCK,
        INPUT_KEY_NUMPAD_0,
        INPUT_KEY_NUMPAD_1,
        INPUT_KEY_NUMPAD_2,
        INPUT_KEY_NUMPAD_3,
        INPUT_KEY_NUMPAD_4,
        INPUT_KEY_NUMPAD_5,
        INPUT_KEY_NUMPAD_6,
        INPUT_KEY_NUMPAD_7,
        INPUT_KEY_NUMPAD_8,
        INPUT_KEY_NUMPAD_9,
        INPUT_KEY_NUMPAD_MULTIPLY,
        INPUT_KEY_NUMPAD_ADD,
        INPUT_KEY_NUMPAD_SEPARATOR,
        INPUT_KEY_NUMPAD_SUBTRACT,
        INPUT_KEY_NUMPAD_DECIMAL,
        INPUT_KEY_NUMPAD_DIVIDE,

        // System / Modifier Keys
        INPUT_KEY_LEFT_SHIFT,
        INPUT_KEY_RIGHT_SHIFT,
        INPUT_KEY_LEFT_CONTROL,
        INPUT_KEY_RIGHT_CONTROL,
        INPUT_KEY_LEFT_ALT,
        INPUT_KEY_RIGHT_ALT,
        INPUT_KEY_LEFT_SUPER,
        INPUT_KEY_RIGHT_SUPER,
        INPUT_KEY_MENU,

        // Browser / Media Keys
        INPUT_KEY_BROWSER_BACK,
        INPUT_KEY_BROWSER_FORWARD,
        INPUT_KEY_BROWSER_REFRESH,
        INPUT_KEY_BROWSER_STOP,
        INPUT_KEY_BROWSER_SEARCH,
        INPUT_KEY_BROWSER_FAVORITES,
        INPUT_KEY_BROWSER_HOME,
        INPUT_KEY_VOLUME_MUTE,
        INPUT_KEY_VOLUME_DOWN,
        INPUT_KEY_VOLUME_UP,
        INPUT_KEY_MEDIA_NEXT_TRACK,
        INPUT_KEY_MEDIA_PREVIOUS_TRACK,
        INPUT_KEY_MEDIA_STOP,
        INPUT_KEY_MEDIA_PLAY_PAUSE,
        INPUT_KEY_LAUNCH_MAIL,
        INPUT_KEY_LAUNCH_MEDIA_SELECT,
        INPUT_KEY_LAUNCH_APP_1,
        INPUT_KEY_LAUNCH_APP_2,

        // Misc / OEM
        INPUT_KEY_OEM_1,
        INPUT_KEY_OEM_2,
        INPUT_KEY_OEM_3,
        INPUT_KEY_OEM_4,
        INPUT_KEY_OEM_5,
        INPUT_KEY_OEM_6,
        INPUT_KEY_OEM_7,
        INPUT_KEY_OEM_8,

        INPUT_KEY_COUNT
    };
}